use_frameworks!

target 'AASheetController_Example' do
  pod 'AASheetController', :path => '../'

  target 'AASheetController_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0'
    pod 'Nimble', '~> 5.0'
  end
end
