use_frameworks!

target 'AASheetController_Example' do
  pod 'AASheetController', :path => '../'

  target 'AASheetController_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
